DROP TABLE IF EXISTS `wdb_gameobject_template`;
CREATE TABLE IF NOT EXISTS `wdb_gameobject_template` (
  `entry` mediumint(8) unsigned NOT NULL,
  `build` smallint(5) unsigned NOT NULL,
  `type` tinyint(3) unsigned DEFAULT NULL,
  `display_id` mediumint(8) unsigned DEFAULT NULL,
  `name` varchar(100) DEFAULT NULL,
  `name2` varchar(100) DEFAULT NULL,
  `name3` varchar(100) DEFAULT NULL,
  `name4` varchar(100) DEFAULT NULL,
  `unk1` varchar(100) DEFAULT NULL,
  `data0` int(10) DEFAULT NULL,
  `data1` int(11) DEFAULT NULL,
  `data2` int(10) DEFAULT NULL,
  `data3` int(10) DEFAULT NULL,
  `data4` int(10) DEFAULT NULL,
  `data5` int(10) DEFAULT NULL,
  `data6` int(11) DEFAULT NULL,
  `data7` int(10) DEFAULT NULL,
  `data8` int(10) DEFAULT NULL,
  `data9` int(10) DEFAULT NULL,
  `data10` int(10) DEFAULT NULL,
  `data11` int(10) DEFAULT NULL,
  `data12` int(10) DEFAULT NULL,
  `data13` int(10) DEFAULT NULL,
  `data14` int(10) DEFAULT NULL,
  `data15` int(10) DEFAULT NULL,
  `data16` int(10) DEFAULT NULL,
  `data17` int(10) DEFAULT NULL,
  `data18` int(10) DEFAULT NULL,
  `data19` int(10) DEFAULT NULL,
  `data20` int(10) DEFAULT NULL,
  `data21` int(10) DEFAULT NULL,
  `data22` int(10) DEFAULT NULL,
  `data23` int(10) DEFAULT NULL,
  PRIMARY KEY (`entry`,`build`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Gameobject System';
