DROP TABLE IF EXISTS `wdb_npc_text`;
CREATE TABLE IF NOT EXISTS `wdb_npc_text` (
  `id` mediumint(8) unsigned NOT NULL,
  `build` smallint(5) unsigned NOT NULL,
  `probability_0` float NOT NULL DEFAULT '0',
  `male_text_0` longtext,
  `female_text_0` longtext,
  `language_id_0` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_0` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_0` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_0` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_0` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_0` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_0` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_1` float NOT NULL DEFAULT '0',
  `male_text_1` longtext,
  `female_text_1` longtext,
  `language_id_1` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_1` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_2` float NOT NULL DEFAULT '0',
  `male_text_2` longtext,
  `female_text_2` longtext,
  `language_id_2` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_2` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_3` float NOT NULL DEFAULT '0',
  `male_text_3` longtext,
  `female_text_3` longtext,
  `language_id_3` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_3` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_4` float NOT NULL DEFAULT '0',
  `male_text_4` longtext,
  `female_text_4` longtext,
  `language_id_4` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_4` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_5` float NOT NULL DEFAULT '0',
  `male_text_5` longtext,
  `female_text_5` longtext,
  `language_id_5` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_5` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_6` float NOT NULL DEFAULT '0',
  `male_text_6` longtext,
  `female_text_6` longtext,
  `language_id_6` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_6` smallint(5) unsigned NOT NULL DEFAULT '0',
  `probability_7` float NOT NULL DEFAULT '0',
  `male_text_7` longtext,
  `female_text_7` longtext,
  `language_id_7` tinyint(3) unsigned NOT NULL DEFAULT '0',
  `emote_delay1_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id1_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay2_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id2_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_delay3_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  `emote_id3_7` smallint(5) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`,`build`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
