DROP TABLE IF EXISTS `wdb_quest_template`;
CREATE TABLE IF NOT EXISTS `wdb_quest_template` (
  `entry` mediumint(8) unsigned NOT NULL,
  `build` smallint(6) unsigned NOT NULL,
  `Method` tinyint(3) unsigned DEFAULT NULL,
  `QuestLevel` tinyint(3) unsigned DEFAULT NULL,
  `ZoneOrSort` smallint(6) DEFAULT NULL,
  `Type` smallint(5) unsigned DEFAULT NULL,
  `RepObjectiveFaction` smallint(5) unsigned DEFAULT NULL,
  `RepObjectiveValue` mediumint(9) DEFAULT NULL,
  `RequiredOppositeRepFaction` smallint(5) unsigned DEFAULT NULL,
  `RequiredOppositeRepValue` mediumint(9) DEFAULT NULL,
  `NextQuestInChain` mediumint(8) unsigned DEFAULT NULL,
  `RewOrReqMoney` int(11) DEFAULT NULL,
  `RewMoneyMaxLevel` int(10) unsigned DEFAULT NULL,
  `RewSpell` smallint(5) unsigned DEFAULT NULL,
  `SrcItemId` mediumint(8) unsigned DEFAULT NULL,
  `QuestFlags` smallint(5) unsigned DEFAULT NULL,
  `RewItemId1` mediumint(8) unsigned DEFAULT NULL,
  `RewItemId2` mediumint(8) unsigned DEFAULT NULL,
  `RewItemId3` mediumint(8) unsigned DEFAULT NULL,
  `RewItemId4` mediumint(8) unsigned DEFAULT NULL,
  `RewItemCount1` smallint(5) unsigned DEFAULT NULL,
  `RewItemCount2` smallint(5) unsigned DEFAULT NULL,
  `RewItemCount3` smallint(5) unsigned DEFAULT NULL,
  `RewItemCount4` smallint(5) unsigned DEFAULT NULL,
  `RewChoiceItemId1` mediumint(8) unsigned DEFAULT NULL,
  `RewChoiceItemId2` mediumint(8) unsigned DEFAULT NULL,
  `RewChoiceItemId3` mediumint(8) unsigned DEFAULT NULL,
  `RewChoiceItemId4` mediumint(8) unsigned DEFAULT NULL,
  `RewChoiceItemId5` mediumint(8) unsigned DEFAULT NULL,
  `RewChoiceItemId6` mediumint(8) unsigned DEFAULT NULL,
  `RewChoiceItemCount1` smallint(5) unsigned DEFAULT NULL,
  `RewChoiceItemCount2` smallint(5) unsigned DEFAULT NULL,
  `RewChoiceItemCount3` smallint(5) unsigned DEFAULT NULL,
  `RewChoiceItemCount4` smallint(5) unsigned DEFAULT NULL,
  `RewChoiceItemCount5` smallint(5) unsigned DEFAULT NULL,
  `RewChoiceItemCount6` smallint(5) unsigned DEFAULT NULL,
  `PointMapId` smallint(5) unsigned DEFAULT NULL,
  `PointX` float DEFAULT NULL,
  `PointY` float DEFAULT NULL,
  `PointOpt` mediumint(8) unsigned DEFAULT NULL,
  `Title` text,
  `Details` text,
  `Objectives` text,
  `EndText` text,
  `ReqCreatureOrGOId1` mediumint(9) DEFAULT NULL,
  `ReqCreatureOrGOId2` mediumint(9) DEFAULT NULL,
  `ReqCreatureOrGOId3` mediumint(9) DEFAULT NULL,
  `ReqCreatureOrGOId4` mediumint(9) DEFAULT NULL,
  `ReqCreatureOrGOCount1` smallint(5) unsigned DEFAULT NULL,
  `ReqCreatureOrGOCount2` smallint(5) unsigned DEFAULT NULL,
  `ReqCreatureOrGOCount3` smallint(5) unsigned DEFAULT NULL,
  `ReqCreatureOrGOCount4` smallint(5) unsigned DEFAULT NULL,
  `ReqItemId1` mediumint(8) unsigned DEFAULT NULL,
  `ReqItemId2` mediumint(8) unsigned DEFAULT NULL,
  `ReqItemId3` mediumint(8) unsigned DEFAULT NULL,
  `ReqItemId4` mediumint(8) unsigned DEFAULT NULL,
  `ReqItemCount1` smallint(5) unsigned DEFAULT NULL,
  `ReqItemCount2` smallint(5) unsigned DEFAULT NULL,
  `ReqItemCount3` smallint(5) unsigned DEFAULT NULL,
  `ReqItemCount4` smallint(5) unsigned DEFAULT NULL,
  `ObjectiveText1` text,
  `ObjectiveText2` text,
  `ObjectiveText3` text,
  `ObjectiveText4` text,
  PRIMARY KEY (`entry`,`build`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COMMENT='Quest System';
