DROP TABLE IF EXISTS `wdb_item_template`;
CREATE TABLE IF NOT EXISTS `wdb_item_template` (
  `entry` mediumint(8) unsigned NOT NULL,
  `build` smallint(5) unsigned NOT NULL,
  `class` tinyint(3) unsigned DEFAULT NULL,
  `subclass` tinyint(3) unsigned DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `name2` varchar(255) DEFAULT NULL,
  `name3` varchar(255) DEFAULT NULL,
  `name4` varchar(255) DEFAULT NULL,
  `display_id` mediumint(8) unsigned DEFAULT NULL,
  `quality` tinyint(3) unsigned DEFAULT NULL,
  `flags` int(10) unsigned DEFAULT NULL,
  `buy_price` int(10) unsigned DEFAULT NULL,
  `sell_price` int(10) unsigned DEFAULT NULL,
  `inventory_type` tinyint(3) unsigned DEFAULT NULL,
  `allowable_class` mediumint(9) DEFAULT NULL,
  `allowable_race` mediumint(9) DEFAULT NULL,
  `item_level` tinyint(3) unsigned DEFAULT NULL,
  `required_level` tinyint(4) DEFAULT NULL,
  `required_skill` smallint(5) unsigned DEFAULT NULL,
  `required_skill_rank` smallint(5) unsigned DEFAULT NULL,
  `required_spell` smallint(5) unsigned DEFAULT NULL,
  `required_honor_rank` mediumint(8) unsigned DEFAULT NULL,
  `required_city_rank` mediumint(8) unsigned DEFAULT NULL,
  `required_reputation_faction` smallint(5) unsigned DEFAULT NULL,
  `required_reputation_rank` smallint(5) unsigned DEFAULT NULL,
  `max_count` smallint(5) unsigned DEFAULT NULL,
  `stackable` smallint(5) unsigned DEFAULT NULL,
  `container_slots` tinyint(3) unsigned DEFAULT NULL,
  `stat_type1` tinyint(3) DEFAULT NULL,
  `stat_value1` smallint(6) DEFAULT NULL,
  `stat_type2` tinyint(3) DEFAULT NULL,
  `stat_value2` smallint(6) DEFAULT NULL,
  `stat_type3` tinyint(3) DEFAULT NULL,
  `stat_value3` smallint(6) DEFAULT NULL,
  `stat_type4` tinyint(3) DEFAULT NULL,
  `stat_value4` smallint(6) DEFAULT NULL,
  `stat_type5` tinyint(3) DEFAULT NULL,
  `stat_value5` smallint(6) DEFAULT NULL,
  `stat_type6` tinyint(3) DEFAULT NULL,
  `stat_value6` smallint(6) DEFAULT NULL,
  `stat_type7` tinyint(3) DEFAULT NULL,
  `stat_value7` smallint(6) DEFAULT NULL,
  `stat_type8` tinyint(3) DEFAULT NULL,
  `stat_value8` smallint(6) DEFAULT NULL,
  `stat_type9` tinyint(3) DEFAULT NULL,
  `stat_value9` smallint(6) DEFAULT NULL,
  `stat_type10` tinyint(3) DEFAULT NULL,
  `stat_value10` smallint(6) DEFAULT NULL,
  `dmg_min1` float DEFAULT NULL,
  `dmg_max1` float DEFAULT NULL,
  `dmg_type1` tinyint(3) unsigned DEFAULT NULL,
  `dmg_min2` float DEFAULT NULL,
  `dmg_max2` float DEFAULT NULL,
  `dmg_type2` tinyint(3) unsigned DEFAULT NULL,
  `dmg_min3` float DEFAULT NULL,
  `dmg_max3` float DEFAULT NULL,
  `dmg_type3` tinyint(3) unsigned DEFAULT NULL,
  `dmg_min4` float DEFAULT NULL,
  `dmg_max4` float DEFAULT NULL,
  `dmg_type4` tinyint(3) unsigned DEFAULT NULL,
  `dmg_min5` float DEFAULT NULL,
  `dmg_max5` float DEFAULT NULL,
  `dmg_type5` tinyint(3) unsigned DEFAULT NULL,
  `armor` smallint(5) DEFAULT NULL,
  `holy_res` smallint(5) DEFAULT NULL,
  `fire_res` smallint(5) DEFAULT NULL,
  `nature_res` smallint(5) DEFAULT NULL,
  `frost_res` smallint(5) DEFAULT NULL,
  `shadow_res` smallint(5) DEFAULT NULL,
  `arcane_res` smallint(5) DEFAULT NULL,
  `delay` smallint(5) unsigned DEFAULT NULL,
  `ammo_type` tinyint(3) unsigned DEFAULT NULL,
  `unk1` int(10) unsigned DEFAULT NULL,
  `range_mod` float DEFAULT NULL,
  `spellid_1` smallint(5) unsigned DEFAULT NULL,
  `spelltrigger_1` tinyint(3) unsigned DEFAULT NULL,
  `spellcharges_1` tinyint(4) DEFAULT NULL,
  `spellcooldown_1` int(11) DEFAULT NULL,
  `spellcategory_1` smallint(5) unsigned DEFAULT NULL,
  `spellcategorycooldown_1` int(11) DEFAULT NULL,
  `spellid_2` smallint(5) unsigned DEFAULT NULL,
  `spelltrigger_2` tinyint(3) unsigned DEFAULT NULL,
  `spellcharges_2` tinyint(4) DEFAULT NULL,
  `spellcooldown_2` int(11) DEFAULT NULL,
  `spellcategory_2` smallint(5) unsigned DEFAULT NULL,
  `spellcategorycooldown_2` int(11) DEFAULT NULL,
  `spellid_3` smallint(5) unsigned DEFAULT NULL,
  `spelltrigger_3` tinyint(3) unsigned DEFAULT NULL,
  `spellcharges_3` tinyint(4) DEFAULT NULL,
  `spellcooldown_3` int(11) DEFAULT NULL,
  `spellcategory_3` smallint(5) unsigned DEFAULT NULL,
  `spellcategorycooldown_3` int(11) DEFAULT NULL,
  `spellid_4` smallint(5) unsigned DEFAULT NULL,
  `spelltrigger_4` tinyint(3) unsigned DEFAULT NULL,
  `spellcharges_4` tinyint(4) DEFAULT NULL,
  `spellcooldown_4` int(11) DEFAULT NULL,
  `spellcategory_4` smallint(5) unsigned DEFAULT NULL,
  `spellcategorycooldown_4` int(11) DEFAULT NULL,
  `spellid_5` smallint(5) unsigned DEFAULT NULL,
  `spelltrigger_5` tinyint(3) unsigned DEFAULT NULL,
  `spellcharges_5` tinyint(4) DEFAULT NULL,
  `spellcooldown_5` int(11) DEFAULT NULL,
  `spellcategory_5` smallint(5) unsigned DEFAULT NULL,
  `spellcategorycooldown_5` int(11) DEFAULT NULL,
  `bonding` tinyint(3) unsigned DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `page_text` mediumint(8) unsigned DEFAULT NULL,
  `page_language` tinyint(3) unsigned DEFAULT NULL,
  `page_material` tinyint(3) unsigned DEFAULT NULL,
  `start_quest` mediumint(8) unsigned DEFAULT NULL,
  `lock_id` mediumint(8) unsigned DEFAULT NULL,
  `material` tinyint(4) DEFAULT NULL,
  `sheath` tinyint(3) unsigned DEFAULT NULL,
  `random_property` mediumint(8) DEFAULT NULL,
  `block` mediumint(8) unsigned DEFAULT NULL,
  `set_id` mediumint(8) unsigned DEFAULT NULL,
  `max_durability` smallint(5) unsigned DEFAULT NULL,
  `area_bound` mediumint(8) unsigned DEFAULT NULL,
  `map_bound` smallint(6) DEFAULT NULL,
  `bag_family` mediumint(9) DEFAULT NULL,
  PRIMARY KEY (`entry`,`build`),
  KEY `items_index` (`class`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Item System';
